server:
  port: 8081

spring:
  datasource:
    #    url: jdbc:mysql://3.107.57.248:3306/foodee_1.2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    #    username: coang
    #    password: coang
    url: jdbc:mysql://localhost:3306/foodee?useSSL=false&serverTimezone=Etc/GMT-7&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenminhcoang@gmail.com
    password: tied foda jgnu akgn
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
  mvc:
    async:
      request-timeout: 180000
  jpa:
    hibernate:
      ddl-auto: none  # "none", "update", "create", "create-drop"
    show-sql: true
    properties:
      hibernate.format_sql: false
    open-in-view: false
