server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodee?useSSL=false&serverTimezone=Etc/GMT-7&allowPublicKeyRetrieval=true&useSSL=false
    #     url: jdbc:mysql://localhost:3306/foodee?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      leak-detection-threshold: 5000
      connection-timeout: 30000  # 30 giây, có thể tăng nếu cần
      idle-timeout: 6000000       # 10 phút
      max-lifetime: 18000000      # 30 phút
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenminhcoang@gmail.com
    password: tied foda jgnu akgn
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
  mvc:
    async:
      request-timeout: 180000
  jpa:
    hibernate:
      ddl-auto: none  # "none", "update", "create", "create-drop"
    show-sql: true
    properties:
      hibernate.format_sql: false
    open-in-view: false